export interface GeminiCallConfig {
  model?: string;
  temperature?: number;
  maxOutputTokens?: number;
  retries?: number;
  timeoutMs?: number;
  apiKey?: string;
  inlineData?: {
    mimeType: string;
    data: string; // base64
  };
}

export const CANDIDATE_GEMINI_MODELS = [
  'gemini-2.0-flash',
  'gemini-1.5-flash',
  'gemini-1.5-pro',
];

/**
 * Strips markdown code fences from JSON output if present.
 */
export function cleanJsonText(raw: string): string {
  let cleaned = raw.trim();
  if (cleaned.startsWith('```json')) {
    cleaned = cleaned.slice(7);
  } else if (cleaned.startsWith('```')) {
    cleaned = cleaned.slice(3);
  }
  if (cleaned.endsWith('```')) {
    cleaned = cleaned.slice(0, -3);
  }
  cleaned = cleaned.trim();
  
  // Extract JSON slice between first { or [ and last } or ]
  const firstBrace = cleaned.indexOf('{');
  const firstBracket = cleaned.indexOf('[');
  let start = -1;
  if (firstBrace !== -1 && firstBracket !== -1) {
    start = Math.min(firstBrace, firstBracket);
  } else if (firstBrace !== -1) {
    start = firstBrace;
  } else if (firstBracket !== -1) {
    start = firstBracket;
  }

  const lastBrace = cleaned.lastIndexOf('}');
  const lastBracket = cleaned.lastIndexOf(']');
  const end = Math.max(lastBrace, lastBracket);

  if (start !== -1 && end !== -1 && end > start) {
    cleaned = cleaned.slice(start, end + 1);
  }

  return cleaned.trim();
}

/**
 * Calls Gemini with structured JSON output enforcement, multi-model cascade, and automatic retries.
 */
export async function callGeminiStructured<T>(
  prompt: string,
  systemInstruction?: string,
  config?: GeminiCallConfig
): Promise<T> {
  const apiKey = config?.apiKey || Deno.env.get('GEMINI_API_KEY') || Deno.env.get('GOOGLE_AI_API_KEY');
  if (!apiKey) {
    throw new Error('GEMINI_API_KEY is not configured. Please set GEMINI_API_KEY in your Supabase project secrets or .env.');
  }

  const candidateModels = config?.model
    ? [config.model, ...CANDIDATE_GEMINI_MODELS.filter((m) => m !== config.model)]
    : CANDIDATE_GEMINI_MODELS;

  const temperature = config?.temperature ?? 0.2;
  const maxRetriesPerModel = config?.retries ?? 1;
  let lastError: Error | null = null;

  const parts: any[] = [];
  if (config?.inlineData?.data) {
    parts.push({
      inlineData: {
        mimeType: config.inlineData.mimeType,
        data: config.inlineData.data,
      },
    });
  }
  parts.push({ text: prompt });

  for (const model of candidateModels) {
    const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;

    for (let attempt = 0; attempt <= maxRetriesPerModel; attempt++) {
      try {
        const response = await fetch(endpoint, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          signal: AbortSignal.timeout(config?.timeoutMs || 25000),
          body: JSON.stringify({
            contents: [{ role: 'user', parts }],
            systemInstruction: systemInstruction
              ? { role: 'system', parts: [{ text: systemInstruction }] }
              : undefined,
            generationConfig: {
              responseMimeType: 'application/json',
              temperature,
              maxOutputTokens: config?.maxOutputTokens || 4096,
            },
          }),
        });

        if (!response.ok) {
          const errText = await response.text();
          const isOverloadedOrNotFound = response.status === 503 || response.status === 404 || response.status === 429;
          
          if (isOverloadedOrNotFound) {
            console.warn(`Gemini model ${model} returned status ${response.status}. Cascading to next candidate model...`);
            lastError = new Error(`Gemini API error (${response.status}): ${errText}`);
            break; // Break inner loop to try next model in candidateModels
          }

          throw new Error(`Gemini API error (${response.status}): ${errText}`);
        }

        const data = await response.json();
        const textOutput = data.candidates?.[0]?.content?.parts?.[0]?.text;
        if (!textOutput) {
          throw new Error(`No candidate text generated by Gemini model ${model}.`);
        }

        const cleaned = cleanJsonText(textOutput);
        return JSON.parse(cleaned) as T;
      } catch (err: any) {
        lastError = err;
        if (attempt < maxRetriesPerModel) {
          await new Promise((resolve) => setTimeout(resolve, (attempt + 1) * 400));
        }
      }
    }
  }

  throw lastError || new Error('Failed to obtain valid JSON from Gemini across all candidate models.');
}

/**
 * Calls Gemini for free-form conversational text output with multi-model cascade.
 */
export async function callGeminiText(
  prompt: string,
  systemInstruction?: string,
  config?: GeminiCallConfig
): Promise<string> {
  const apiKey = config?.apiKey || Deno.env.get('GEMINI_API_KEY') || Deno.env.get('GOOGLE_AI_API_KEY');
  if (!apiKey) {
    throw new Error('GEMINI_API_KEY is not configured. Please set GEMINI_API_KEY in your Supabase project secrets or .env.');
  }

  const candidateModels = config?.model
    ? [config.model, ...CANDIDATE_GEMINI_MODELS.filter((m) => m !== config.model)]
    : CANDIDATE_GEMINI_MODELS;

  const temperature = config?.temperature ?? 0.7;
  const maxRetriesPerModel = config?.retries ?? 1;
  let lastError: Error | null = null;

  const parts: any[] = [];
  if (config?.inlineData?.data) {
    parts.push({
      inlineData: {
        mimeType: config.inlineData.mimeType,
        data: config.inlineData.data,
      },
    });
  }
  parts.push({ text: prompt });

  for (const model of candidateModels) {
    const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;

    for (let attempt = 0; attempt <= maxRetriesPerModel; attempt++) {
      try {
        const response = await fetch(endpoint, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          signal: AbortSignal.timeout(config?.timeoutMs || 25000),
          body: JSON.stringify({
            contents: [{ role: 'user', parts }],
            systemInstruction: systemInstruction
              ? { role: 'system', parts: [{ text: systemInstruction }] }
              : undefined,
            generationConfig: {
              temperature,
              maxOutputTokens: config?.maxOutputTokens || 2048,
            },
          }),
        });

        if (!response.ok) {
          const errText = await response.text();
          const isOverloadedOrNotFound = response.status === 503 || response.status === 404 || response.status === 429;
          
          if (isOverloadedOrNotFound) {
            console.warn(`Gemini text model ${model} returned status ${response.status}. Cascading to next candidate model...`);
            lastError = new Error(`Gemini API text error (${response.status}): ${errText}`);
            break; // Break inner loop to try next model in candidateModels
          }

          throw new Error(`Gemini API text error (${response.status}): ${errText}`);
        }

        const data = await response.json();
        const textOutput = data.candidates?.[0]?.content?.parts?.[0]?.text;
        if (!textOutput) {
          throw new Error(`No text generated by Gemini model ${model}.`);
        }

        return textOutput.trim();
      } catch (err: any) {
        lastError = err;
        if (attempt < maxRetriesPerModel) {
          await new Promise((resolve) => setTimeout(resolve, (attempt + 1) * 400));
        }
      }
    }
  }

  throw lastError || new Error('Failed to obtain text from Gemini across all candidate models.');
}
