export interface GeminiCallConfig {
  model?: string;
  temperature?: number;
  maxOutputTokens?: number;
  retries?: number;
  apiKey?: string;
}

/**
 * Strips markdown code fences from JSON output if present.
 */
export function cleanJsonText(raw: string): string {
  let cleaned = raw.trim();
  if (cleaned.startsWith('```json')) {
    cleaned = cleaned.slice(7);
  } else if (cleaned.startsWith('```')) {
    cleaned = cleaned.slice(3);
  }
  if (cleaned.endsWith('```')) {
    cleaned = cleaned.slice(0, -3);
  }
  return cleaned.trim();
}

/**
 * Calls Gemini with structured JSON output enforcement and automatic retries.
 */
export async function callGeminiStructured<T>(
  prompt: string,
  systemInstruction?: string,
  config?: GeminiCallConfig
): Promise<T> {
  const apiKey = config?.apiKey || Deno.env.get('GEMINI_API_KEY') || Deno.env.get('GOOGLE_AI_API_KEY');
  if (!apiKey) {
    throw new Error('GEMINI_API_KEY is not configured. Please set GEMINI_API_KEY in your Supabase project secrets or .env.');
  }

  const model = config?.model || 'gemini-flash-latest';
  const temperature = config?.temperature ?? 0.2;
  const maxRetries = config?.retries ?? 2;
  const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;

  let lastError: Error | null = null;

  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    try {
      const response = await fetch(endpoint, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [{ role: 'user', parts: [{ text: prompt }] }],
          systemInstruction: systemInstruction
            ? { role: 'system', parts: [{ text: systemInstruction }] }
            : undefined,
          generationConfig: {
            responseMimeType: 'application/json',
            temperature,
            maxOutputTokens: config?.maxOutputTokens || 4096,
          },
        }),
      });

      if (!response.ok) {
        const errText = await response.text();
        throw new Error(`Gemini API error (${response.status}): ${errText}`);
      }

      const data = await response.json();
      const textOutput = data.candidates?.[0]?.content?.parts?.[0]?.text;
      if (!textOutput) {
        throw new Error('No candidate text generated by Gemini.');
      }

      const cleaned = cleanJsonText(textOutput);
      return JSON.parse(cleaned) as T;
    } catch (err: any) {
      lastError = err;
      if (attempt < maxRetries) {
        console.warn(`Gemini attempt ${attempt + 1} failed (${err.message}). Retrying in ${(attempt + 1) * 500}ms...`);
        await new Promise((resolve) => setTimeout(resolve, (attempt + 1) * 500));
      }
    }
  }

  throw lastError || new Error('Failed to obtain valid JSON from Gemini.');
}

/**
 * Calls Gemini for free-form conversational text output.
 */
export async function callGeminiText(
  prompt: string,
  systemInstruction?: string,
  config?: GeminiCallConfig
): Promise<string> {
  const apiKey = config?.apiKey || Deno.env.get('GEMINI_API_KEY') || Deno.env.get('GOOGLE_AI_API_KEY');
  if (!apiKey) {
    throw new Error('GEMINI_API_KEY is not configured. Please set GEMINI_API_KEY in your Supabase project secrets or .env.');
  }

  const model = config?.model || 'gemini-flash-latest';
  const temperature = config?.temperature ?? 0.7;
  const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;

  const response = await fetch(endpoint, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      contents: [{ role: 'user', parts: [{ text: prompt }] }],
      systemInstruction: systemInstruction
        ? { role: 'system', parts: [{ text: systemInstruction }] }
        : undefined,
      generationConfig: {
        temperature,
        maxOutputTokens: config?.maxOutputTokens || 2048,
      },
    }),
  });

  if (!response.ok) {
    const errText = await response.text();
    throw new Error(`Gemini API text error (${response.status}): ${errText}`);
  }

  const data = await response.json();
  const textOutput = data.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!textOutput) {
    throw new Error('No text generated by Gemini.');
  }

  return textOutput.trim();
}
